baseURL = 'https://foilingspots.com/'
languageCode = 'en-gb'
title = 'Foilingspots'
enableGitInfo = true

[module]
[[module.imports]]
    path = 'github.com/gohugoio/hugo-mod-bootstrap-scss/v5'

[params]
    description = "Foilingspots, a lists of the best foiling spots around."
    mapsApiKey = 'AIzaSyDd_OBa53YAF97So9f2Yg55wTRF2HLN3pk'
    [params.homepage_meta_tags]
        meta_og_title = "Foilingspots"
        meta_og_type = "website"
        meta_og_url = "https://foilingspots.com"